export const abrevToName = {
  abw: 'Aruba',
  afg: 'Afghanistan',
  ago: 'Angola',
  aia: 'Anguilla',
  alb: 'Albania',
  ala: 'Åland',
  and: 'Andorra',
  are: 'United Arab Emirates',
  arg: 'Argentina',
  arm: 'Armenia',
  asm: 'American Samoa',
  ata: 'Antarctica',
  atf: 'Fr. S. Antarctic Lands',
  atg: 'Antigua and Barb.',
  aus: 'Australia',
  aut: 'Austria',
  aze: 'Azerbaijan',
  bdi: 'Burundi',
  bel: 'Belgium',
  ben: 'Benin',
  bfa: 'Burkina Faso',
  bgd: 'Bangladesh',
  bgr: 'Bulgaria',
  bhr: 'Bahrain',
  bhs: 'Bahamas',
  bih: 'Bosnia and Herz.',
  blm: 'St-Barthélemy',
  blr: 'Belarus',
  blz: 'Belize',
  bmu: 'Bermuda',
  bol: 'Bolivia',
  bra: 'Brazil',
  brb: 'Barbados',
  brn: 'Brunei',
  btn: 'Bhutan',
  bwa: 'Botswana',
  caf: 'Central African Rep.',
  can: 'Canada',
  che: 'Switzerland',
  chl: 'Chile',
  chn: 'China',
  civ: "Côte d'Ivoire",
  cmr: 'Cameroon',
  cod: 'Dem. Rep. Congo',
  cog: 'Congo',
  cok: 'Cook Is.',
  col: 'Colombia',
  com: 'Comoros',
  cpv: 'Cabo Verde',
  cri: 'Costa Rica',
  cub: 'Cuba',
  cuw: 'Curaçao',
  cym: 'Cayman Is.',
  cyp: 'Cyprus',
  cze: 'Czechia',
  deu: 'Germany',
  dji: 'Djibouti',
  dma: 'Dominica',
  dnk: 'Denmark',
  dom: 'Dominican Rep.',
  dza: 'Algeria',
  ecu: 'Ecuador',
  egy: 'Egypt',
  eri: 'Eritrea',
  esp: 'Spain',
  est: 'Estonia',
  eth: 'Ethiopia',
  fin: 'Finland',
  fji: 'Fiji',
  flk: 'Falkland Is.',
  fra: 'France',
  fro: 'Faeroe Is.',
  fsm: 'Micronesia',
  gab: 'Gabon',
  gbr: 'United Kingdom',
  geo: 'Georgia',
  ggy: 'Guernsey',
  gha: 'Ghana',
  gin: 'Guinea',
  gmb: 'Gambia',
  gnb: 'Guinea-Bissau',
  gnq: 'Eq. Guinea',
  grc: 'Greece',
  grd: 'Grenada',
  grl: 'Greenland',
  gtm: 'Guatemala',
  gum: 'Guam',
  guy: 'Guyana',
  hkg: 'Hong Kong',
  hmd: 'Heard I. and McDonald Is.',
  hnd: 'Honduras',
  hrv: 'Croatia',
  hti: 'Haiti',
  hun: 'Hungary',
  idn: 'Indonesia',
  imn: 'Isle of Man',
  ind: 'India',
  iot: 'Br. Indian Ocean Ter.',
  irl: 'Ireland',
  irn: 'Iran',
  irq: 'Iraq',
  isl: 'Iceland',
  isr: 'Israel',
  ita: 'Italy',
  jam: 'Jamaica',
  jey: 'Jersey',
  jor: 'Jordan',
  jpn: 'Japan',
  kaz: 'Kazakhstan',
  ken: 'Kenya',
  kgz: 'Kyrgyzstan',
  khm: 'Cambodia',
  kir: 'Kiribati',
  kna: 'St. Kitts and Nevis',
  kor: 'South Korea',
  kwt: 'Kuwait',
  lao: 'Laos',
  lbn: 'Lebanon',
  lbr: 'Liberia',
  lby: 'Libya',
  lca: 'Saint Lucia',
  lie: 'Liechtenstein',
  lka: 'Sri Lanka',
  lso: 'Lesotho',
  ltu: 'Lithuania',
  lux: 'Luxembourg',
  lva: 'Latvia',
  mac: 'Macao',
  maf: 'St-Martin',
  mar: 'Morocco',
  mco: 'Monaco',
  mda: 'Moldova',
  mdg: 'Madagascar',
  mdv: 'Maldives',
  mex: 'Mexico',
  mhl: 'Marshall Is.',
  mkd: 'Macedonia',
  mli: 'Mali',
  mlt: 'Malta',
  mmr: 'Myanmar',
  mne: 'Montenegro',
  mng: 'Mongolia',
  mnp: 'N. Mariana Is.',
  moz: 'Mozambique',
  mrt: 'Mauritania',
  msr: 'Montserrat',
  mus: 'Mauritius',
  mwi: 'Malawi',
  mys: 'Malaysia',
  nam: 'Namibia',
  ncl: 'New Caledonia',
  ner: 'Niger',
  nfk: 'Norfolk Island',
  nga: 'Nigeria',
  nic: 'Nicaragua',
  niu: 'Niue',
  nld: 'Netherlands',
  nor: 'Norway',
  npl: 'Nepal',
  nru: 'Nauru',
  nzl: 'New Zealand',
  omn: 'Oman',
  pak: 'Pakistan',
  pan: 'Panama',
  pcn: 'Pitcairn Is.',
  per: 'Peru',
  phl: 'Philippines',
  plw: 'Palau',
  png: 'Papua New Guinea',
  pol: 'Poland',
  pri: 'Puerto Rico',
  prk: 'North Korea',
  prt: 'Portugal',
  pry: 'Paraguay',
  pse: 'Palestine',
  pyf: 'Fr. Polynesia',
  qat: 'Qatar',
  rou: 'Romania',
  rus: 'Russia',
  rwa: 'Rwanda',
  esh: 'W. Sahara',
  sau: 'Saudi Arabia',
  sdn: 'Sudan',
  ssd: 'S. Sudan',
  sen: 'Senegal',
  sgp: 'Singapore',
  sgs: 'S. Geo. and the Is.',
  shn: 'Saint Helena',
  slb: 'Solomon Is.',
  sle: 'Sierra Leone',
  slv: 'El Salvador',
  smr: 'San Marino',
  som: 'Somalia',
  spm: 'St. Pierre and Miquelon',
  srb: 'Serbia',
  stp: 'São Tomé and Principe',
  sur: 'Suriname',
  svk: 'Slovakia',
  svn: 'Slovenia',
  swe: 'Sweden',
  swz: 'Swaziland',
  sxm: 'Sint Maarten',
  syc: 'Seychelles',
  syr: 'Syria',
  tca: 'Turks and Caicos Is.',
  tcd: 'Chad',
  tgo: 'Togo',
  tha: 'Thailand',
  tjk: 'Tajikistan',
  tkm: 'Turkmenistan',
  tls: 'Timor-Leste',
  ton: 'Tonga',
  tto: 'Trinidad and Tobago',
  tun: 'Tunisia',
  tur: 'Turkey',
  twn: 'Taiwan',
  tza: 'Tanzania',
  uga: 'Uganda',
  ukr: 'Ukraine',
  ury: 'Uruguay',
  usa: 'United States of America',
  uzb: 'Uzbekistan',
  vat: 'Vatican',
  vct: 'St. Vin. and Gren.',
  ven: 'Venezuela',
  vgb: 'British Virgin Is.',
  vir: 'U.S. Virgin Is.',
  vnm: 'Vietnam',
  vut: 'Vanuatu',
  wlf: 'Wallis and Futuna Is.',
  wsm: 'Samoa',
  yem: 'Yemen',
  zaf: 'South Africa',
  zmb: 'Zambia',
  zwe: 'Zimbabwe'
};
