export const CHANGE_SETTINGS_MAP = 'CHANGE_SETTINGS_MAP';
export const CHANGE_SETTINGS_NEURAL_NET = 'CHANGE_SETTINGS_NEURAL_NET';
export const SET_PARSER_FREQUNCY = 'SET_PARSER_FREQUNCY';
export const SET_INTERVAL_ID = 'SET_INTERVAL_ID';
export const DELETE_INTERVAL_ID = 'DELETE_INTERVAL_ID';
