//@flow

export const GET_SOURCES_REQUEST = 'GET_SOURCES_REQUEST';
export const GET_SOURCES_FAILURE = 'GET_SOURCES_FAILURE';
export const GET_SOURCES_SUCCESS = 'GET_SOURCES_SUCCESS';
export const TRYING_DELETE = 'TRYING_DELETE';
export const SEARCH_SOURCE = 'SEARCH_SOURCE';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const SORT_SOURCES_BY_DATE = 'SORT_SOURCES_BY_DATE';
export const SORT_SOURCES_BY_NAME = 'SORT_SOURCES_BY_NAME';
